AltTexture {
    key = 'tarots',
    set = 'Tarot',
    path = 'Tarots.png',
    keys = {
        'c_fool',
        'c_magician',
        'c_high_priestess',
        'c_empress',
        'c_emperor',
        'c_heirophant',
        'c_lovers',
        'c_chariot',
        'c_justice',
        'c_hermit',
        'c_wheel_of_fortune',
        'c_strength',
        'c_hanged_man',
        'c_death',
        'c_temperance',
        'c_devil',
        'c_tower',
        'c_star',
        'c_moon',
        'c_sun',
        'c_judgement',
        'c_world',

    },
    soul_keys = {
        'c_fool',
        'c_magician',
        'c_high_priestess',
        'c_empress',
        'c_emperor',
        'c_heirophant',
        'c_lovers',
        'c_chariot',
        'c_justice',
        'c_hermit',
        'c_wheel_of_fortune',
        'c_strength',
        'c_hanged_man',
        'c_death',
        'c_temperance',
        'c_devil',
        'c_tower',
        'c_star',
        'c_moon',
        'c_sun',
        'c_judgement',
        'c_world',
    },
}

AltTexture {
    key = 'vouchers',
    set = 'Voucher',
    path = 'Vouchers.png',
    keys = {
        'v_overstock_norm',
        'v_clearance_sale',
        'v_hone',
        'v_reroll_surplus',
        'v_crystal_ball',
        'v_telescope',
        'v_grabber',
        'v_wasteful',
        'v_tarot_merchant',
        'v_planet_merchant',
        'v_seed_money',
        'v_blank',
        'v_magic_trick',
        'v_hieroglyph',
        'v_directors_cut',
        'v_paint_brush',
        'v_overstock_plus',
        'v_liquidation',
        'v_glow_up',
        'v_reroll_glut',
        'v_omen_globe',
        'v_observatory',
        'v_nacho_tong',
        'v_recyclomancy',
        'v_tarot_tycoon',
        'v_planet_tycoon',
        'v_money_tree',
        'v_antimatter',
        'v_illusion',
        'v_petroglyph',
        'v_retcon',
        'v_palette',
    },
    soul_keys = {
        'v_overstock_norm',
        'v_clearance_sale',
        'v_hone',
        'v_reroll_surplus',
        'v_crystal_ball',
        'v_telescope',
        'v_grabber',
        'v_wasteful',
        'v_tarot_merchant',
        'v_planet_merchant',
        'v_seed_money',
        'v_blank',
        'v_magic_trick',
        'v_hieroglyph',
        'v_directors_cut',
        'v_paint_brush',
        'v_overstock_plus',
        'v_liquidation',
        'v_glow_up',
        'v_reroll_glut',
        'v_omen_globe',
        'v_observatory',
        'v_nacho_tong',
        'v_recyclomancy',
        'v_tarot_tycoon',
        'v_planet_tycoon',
        'v_money_tree',
        'v_antimatter',
        'v_illusion',
        'v_petroglyph',
        'v_retcon',
        'v_palette',
    },
}

TexturePack {
    key = 'soul_tarots',
    textures = {
        'soul_tarots_tarots',
        'soul_tarots_vouchers',
    },
}
