AltTexture {
    key = 'planets',
    set = 'Planet',
    path = 'Planets.png',
    keys = {
        'c_pluto',
        'c_mercury',
        'c_uranus',
        'c_venus',
        'c_saturn',
        'c_jupiter',
        'c_earth',
        'c_mars',
        'c_neptune',
        'c_planet_x',
        'c_ceres',
        'c_eris',
        'c_black_hole',
    },
    soul_keys = {
        'c_pluto',
        'c_mercury',
        'c_uranus',
        'c_venus',
        'c_saturn',
        'c_jupiter',
        'c_earth',
        'c_mars',
        'c_neptune',
        'c_planet_x',
        'c_ceres',
        'c_eris',
        'c_black_hole',
    }
}